---

- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (Ubuntu)
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Fedora)
    dnf:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache & PHP packages for Ubuntu
    apt:
     name:
      - apache2
      - libapache2-mod-php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache & PHP packages for Fedora
    dnf:
     name:
      - httpd
      - php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    apt: 
     name: mariadb-server
     state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (Fedora)
    dnf:
     name: mariadb
     state: latest
    when: ansible_distribution == "Fedora"

