---

- hosts: all
  become: true
  pre_tasks:
 
  - name: install updates (Ubuntu)
    tags: always
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Fedora)
    tags: always
    dnf:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache & PHP packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
     name:
      - apache2
      - libapache2-mod-php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd & PHP packages for Fedora
    tags: apache,fedora,httpd
    dnf:
     name:
      - httpd
      - php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: ubuntu,os,mariadb
    apt: 
     name: mariadb-server
     state: latest
    when: ansible_distribution == "Ubuntu"
    ignore_errors: yes

  - name: install mariadb package (Fedora)
    tags: fedora,os,mariadb
    dnf:
     name: mariadb
     state: latest
    when: ansible_distribution == "Fedora"
    ignore_errors: yes

- hosts: file_servers 
  tags: samba
  become: true 
  tasks: 
   
  - name: install samba package 
    package: 
      name: samba 
      state: latest

